# Generated by Django 5.2.7 on 2025-11-05 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('pickup_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('dropoff_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('dropoff_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('BK', 'Booked'), ('PU', 'Pick-Up'), ('CA', 'Cancelled'), ('ER', 'En-route'), ('DO', 'Drop-off'), ('CP', 'Completed')], default='BK', max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
