# Generated by Django 5.2.7 on 2025-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ride_driver_alter_ride_rider_rideevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('PU', 'Pick-Up'), ('CA', 'Cancelled'), ('ER', 'En-route'), ('DO', 'Drop-off'), ('CP', 'Completed')], default='PU', max_length=15),
        ),
    ]
